name: ðŸš€ Diff test
run-name: ðŸš€ Diff test

on:
  workflow_dispatch:

jobs:
  record-diff:
    runs-on: ubuntu-latest
    name: Record diff
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge branch
        run: |
          git checkout prod
          git rebase main
          git push origin prod
    
